### ISSUE TITLE
Release 0.0.4 is broken

### ISSUE THREAD

**Issue by kfktwo** [ribtoks/kanboard-tdg-import#2]
The zip file is missing the directory separator in all of the paths; the files are TdgImportFilename instead of TdgImport/Filename, this results in the plugin not working when extracted.

**Comment by ribtoks** [comment]
Hey @r3dey3 
Thanks for reporting it! 
Indeed, I used `--prefix=TdgImport` for `git archive` that was a mistake. I reuploaded release. It should be better now.
